# Generated by Django 2.2.5 on 2021-04-04 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bkashuserpaymanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=255)),
                ('Ammount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='costprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='location_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='package_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pon_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_loca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('user_phone_number', models.CharField(max_length=255)),
                ('user_onu_macaddr', models.CharField(max_length=255)),
                ('payment', models.TextField()),
                ('user_LOCATION', models.TextField()),
                ('activition_date', models.DateTimeField()),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.package_list')),
                ('pon_listf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.pon_list')),
                ('user_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.user_loc')),
            ],
        ),
        migrations.CreateModel(
            name='profileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Asn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VLAN', models.IntegerField()),
                ('DESCRIPTION', models.TextField()),
                ('LOCATION', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='login_register.location_model')),
            ],
        ),
        migrations.CreateModel(
            name='dailybilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cost', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateES', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.costprofile')),
            ],
        ),
    ]
