# Generated by Django 3.1.3 on 2020-11-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_post_asn'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post_asn',
            name='LOCATION',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='login_register.location_model'),
        ),
    ]
