# Generated by Django 2.2.5 on 2020-11-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20201107_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_model',
            old_name='loc',
            new_name='Location',
        ),
    ]
