# Generated by Django 2.2.5 on 2021-01-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_auto_20201108_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pon_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_loca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('user_phone_number', models.CharField(max_length=255)),
                ('user_onu_macaddr', models.CharField(max_length=255)),
                ('payment', models.TextField()),
                ('user_LOCATION', models.TextField()),
                ('activition_date', models.DateTimeField()),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.package_list')),
                ('pon_listf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.pon_list')),
                ('user_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.user_loc')),
            ],
        ),
    ]
