# Generated by Django 2.2.5 on 2021-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_package_list_pon_list_user_loc_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='costprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=255)),
            ],
        ),
    ]
