# Generated by Django 2.2.5 on 2021-03-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_costprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailybilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('cost_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.costprofile')),
            ],
        ),
    ]
