# Generated by Django 2.2.5 on 2021-03-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_dailybilling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybilling',
            name='cost',
            field=models.CharField(max_length=255),
        ),
    ]
