# Generated by Django 2.2.5 on 2021-03-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_auto_20210315_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybilling',
            name='dateES',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
