# Generated by Django 2.2.5 on 2021-03-22 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_dailybilling_datees'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybilling',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
