# Generated by Django 2.2.5 on 2021-04-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0010_dailybilling_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='bkashuserpaymanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=255)),
                ('Ammount', models.CharField(max_length=255)),
            ],
        ),
    ]
